# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7651264d9706b2eb8f3ee10269a5944b"
name = "loyalty-points-app"
handle = "loyalty-points-app-5"
application_url = "https://3c2cb21bd1f4.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://3c2cb21bd1f4.ngrok-free.app/auth/callback", "https://3c2cb21bd1f4.ngrok-free.app/auth/shopify/callback", "https://3c2cb21bd1f4.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
